"""`alfred schedule` — emit a ready-to-use daily schedule for `alfred watch`.

The product is a *daily* digest, but `alfred.watch.watch_once` is a single
pass by design (ADR 0007 §1: no daemon, "cron-friendly", re-run via cron).
This module makes that promise concrete without adding any infra, for the two
places a daily run can live:

- `build_cron_line` — one crontab entry, for a host you keep running.
- `build_github_actions_workflow` — a committable workflow, for the (common)
  case where no such host exists and the digest would otherwise stop the day
  the laptop closes. See docs/adr/0027-unattended-daily-digest.md.

Both are pure string generation — no scheduling process, trivially testable.

See docs/adr/0007-brique5-delivery-cli-design.md §1.
"""

from __future__ import annotations

import json
import shlex
from pathlib import Path

# Pinned so a generated workflow is reproducible; bumped deliberately, not by
# a floating tag that could change what a user already committed.
_CHECKOUT_ACTION = "actions/checkout@v4"
_SETUP_PYTHON_ACTION = "actions/setup-python@v5"
_CACHE_ACTION = "actions/cache@v4"
_WORKFLOW_PYTHON_VERSION = "3.12"
# The state directory `alfred watch` writes: `seen.json` (what has already been
# ingested and digested) and the SQLite trace store behind the baseline window.
_STATE_DIR = ".alfred"
_CACHE_KEY_PREFIX = "alfred-state-"


class ScheduleError(Exception):
    """Raised when a schedule cannot be built (e.g. an out-of-range time)."""


def _validate_time(hour: int, minute: int) -> None:
    """Raise `ScheduleError` unless `hour:minute` is a real time of day.

    Fail loudly rather than emit a schedule the scheduler would silently
    reject — a digest that never fires is indistinguishable from an agent
    that did nothing.
    """
    if not 0 <= hour < 24:
        raise ScheduleError(f"hour must be in 0..23, got {hour}")
    if not 0 <= minute < 60:
        raise ScheduleError(f"minute must be in 0..59, got {minute}")


def build_cron_line(
    project_dir: Path | str,
    traces_dir: Path | str,
    *,
    hour: int,
    minute: int,
    alfred_bin: str = "alfred",
) -> str:
    """Return one crontab line running `alfred watch` daily at `hour:minute`.

    Paths are resolved to absolute so the line works from cron's bare
    environment (whose working directory is not the project). Raises
    `ScheduleError` if the time is out of range — fail loudly rather than
    emit a crontab line cron would silently reject.
    """
    _validate_time(hour, minute)

    project_abs = Path(project_dir).resolve()
    traces_abs = Path(traces_dir).resolve()
    command = f"{alfred_bin} watch {traces_abs} --project {project_abs}"
    return f"{minute} {hour} * * * {command}"


def build_github_actions_workflow(
    traces_dir: Path | str,
    *,
    hour: int,
    minute: int,
) -> str:
    """Return a GitHub Actions workflow running `alfred watch` daily, as YAML.

    Unlike `build_cron_line`, `traces_dir` stays **relative**: a runner checks
    the repository out at a path unknown when this file is written, so an
    absolute path would point at nothing. An absolute one is refused rather
    than silently rewritten (ADR 0027 decision 3).

    The Slack webhook is read from the `ALFRED_SLACK_WEBHOOK_URL` repository
    secret, never written into the committed file — a webhook's path is its
    credential (ADR 0025 decision 7).

    Raises `ScheduleError` if the time is out of range or the path is absolute.
    """
    _validate_time(hour, minute)

    traces = Path(traces_dir)
    if traces.is_absolute():
        raise ScheduleError(
            f"traces_dir must be relative to the repository root for a workflow, "
            f"got the absolute path {traces}"
        )

    # Two layers to cross, so two quotings: `shlex.quote` makes the path a
    # single shell word, `json.dumps` makes the resulting command a valid
    # double-quoted YAML scalar (ADR 0027 decision 8).
    watch_command = json.dumps(f"alfred watch {shlex.quote(traces.as_posix())}")

    return f"""\
# Alfred — daily digest, run by GitHub Actions.
#
# Generated by `alfred schedule <traces> --at HH:MM --github-actions`.
# Commit this file under .github/workflows/, commit your mandate.yaml next to
# it, and add the repository secret ALFRED_SLACK_WEBHOOK_URL under
# Settings -> Secrets and variables -> Actions.
#
# The schedule is UTC. GitHub cron has no local time zone, unlike the crontab
# line `alfred schedule` prints for a host you own.
#
# State ({_STATE_DIR}/) is cached between runs so a digest is not posted twice and
# the baseline window keeps its history. A GitHub cache is evictable by
# design: after a miss, the day's digest is recomputed and posted again.

name: Alfred daily digest

on:
  schedule:
    - cron: "{minute} {hour} * * *"
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: {_CHECKOUT_ACTION}
      - uses: {_SETUP_PYTHON_ACTION}
        with:
          python-version: "{_WORKFLOW_PYTHON_VERSION}"
      - uses: {_CACHE_ACTION}
        with:
          path: {_STATE_DIR}
          key: {_CACHE_KEY_PREFIX}${{{{ github.run_id }}}}
          restore-keys: {_CACHE_KEY_PREFIX}
      - run: pip install alfred-ai
      - name: Bootstrap the project config when the cache was empty
        run: |
          mkdir -p {_STATE_DIR}
          test -f {_STATE_DIR}/config.toml || printf '%s\\n%s\\n' \\
            'mandate_path = "mandate.yaml"' \\
            'trace_db_path = "{_STATE_DIR}/trace.db"' > {_STATE_DIR}/config.toml
      - name: Compute and deliver the digest
        run: {watch_command}
        env:
          ALFRED_SLACK_WEBHOOK_URL: ${{{{ secrets.ALFRED_SLACK_WEBHOOK_URL }}}}
"""
